# neosr-train D:\Users\Sirosky\Icedrive\Upscaling\Trainers\neosr\options\2x_AniSD_ABO_RPLKSR_i2.toml --auto_resume
# tensorboard --logdir D:\Users\Sirosky\Icedrive\Upscaling\Trainers\neosr\experiments\tb_logger\2x_AniSD_ABO_RPLKSR_i2
# Stopped at 197,500.


name = "2x_AniSD_ABO_RPLKSR_i2"
model_type = "image"
scale = 2
use_amp = true
bfloat16 = true
fast_matmul = true
# manual_seed = 1024

[datasets.train]
type = "paired"
dataroot_gt = "C:/Datasets/[Gen 6] Dataset - AniSD ABO Pruned/HR/"
dataroot_lq = "C:/Datasets/[Gen 6] Dataset - AniSD ABO Pruned/LR/"
patch_size = 256 #64 96 256
batch_size = 4 #16 24 4
accumulate = 3
#augmentation = [ "none", "mixup", "cutmix", "resizemix" ] # [ "cutblur" ]
#aug_prob = [ 0.5, 0.1, 0.1, 0.1 ] # [ 0.7 ]


[datasets.val]
name = "val"
type = "paired"
dataroot_gt = "D:/Users/Sirosky/Icedrive/Datasets/Validation/2x_AniSD_DC/HR/"
dataroot_lq = "D:/Users/Sirosky/Icedrive/Datasets/Validation/2x_AniSD_DC/LR/"
[val]
val_freq = 2500
#tile = 200
[val.metrics.psnr]
type = "calculate_psnr"
[val.metrics.ssim]
type = "calculate_ssim"
[val.metrics.dists]
type = "calculate_dists"
better = "lower"

[path]
pretrain_network_g = "D:/Users/Sirosky/Icedrive/Upscaling/Models Main/[AniSD PTH]/2x_AniSD_RealPLKSR_140K.pth"
strict_load_g = true
# resume_state = "D:/Users/Sirosky/Icedrive/Upscaling/Trainers/neosr/experiments/2x_AniSD_ABO_RPLKSR_i2/training_states/30000.state"

[network_g]
type = "realplksr"

[network_d]
type = "patchgan"

[train]
ema = 0.999
wavelet_guided = false
wavelet_init = 80000
# grad_clip = false # used for soap_sf
#sam = "fsam"
#sam_init = 1000
#eco = true
#eco_init = 15000
#match_lq_colors = true

[train.optim_g]
type = "adan_sf"
lr = 8e-4
betas = [ 0.98, 0.92, 0.99 ]
weight_decay = 0.01
schedule_free = true
warmup_steps = 1600

[train.optim_d]
type = "adan_sf"
lr = 1e-4
betas = [ 0.98, 0.92, 0.99 ]
weight_decay = 0.01
schedule_free = true
warmup_steps = 600

#  losses
[train.mssim_opt]
type = "mssim_loss"
loss_weight = 1.0

[train.ldl_opt]
type = "ldl_loss"
loss_weight = 1.0

[train.gan_opt]
type = "gan_loss"
gan_type = "bce"
loss_weight = 0.1

[train.perceptual_opt]
type = "vgg_perceptual_loss"
loss_weight = 0.5
criterion = "huber"
##patchloss = true
##ipk = true
##patch_weight = 1.0

[train.dists_opt]
type = "dists_loss"
loss_weight = 0.5


[logger]
total_iter = 99999999
save_checkpoint_freq = 2500
use_tb_logger = true
#save_tb_img = true
#print_freq = 100
